### ISSUE TITLE
Enable cirrus-ci for FreeBSD builds

### ISSUE THREAD

**Issue by xobs** [litex-hub/wishbone-utils#1]
FreeBSD binaries cannot be built on Travis: https://github.com/xobs/wishbone-utils/pull/14

As an alternative, we can build these on Cirrus-CI.  In order to do that, cirrus-ci integration must be enabled for the `litex-hub` organization: https://cirrus-ci.org/guide/quick-start/

**Comment by enjoy-digital** [comment]
This should be done (and you should also be able to do manage apps yourself directly in litex-hub now).

**Comment by xobs** [comment]
Thanks, @enjoy-digital -- it's enabled now.

Note that I don't appear to have the ability to manage apps -- when I try it says ` This action must be performed by an organization owner`.

**Comment by enjoy-digital** [comment]
OK, you're now an organization owner so should be able to manage apps :)
