### ISSUE TITLE
wishbone-tool --server gdb - XML target description?

### ISSUE THREAD

**Issue by mithro** [litex-hub/wishbone-utils#17]
Using the `riscv32-elf-gdb` binary from the following package;
```
    gdb-riscv32-elf-8.2        |  20200108_150345         5.5 MB  timvideos
```

After doing a `target remote localhost:1234` I get the following warning;
```
warning: Can not parse XML target description; XML support was disabled at compile time
```

Any idea what I need to do to support this and what the support would give me?

**Comment by xobs** [comment]
That's an issue with your gdb version.

Gdb supports a target.xml file that describes the chip, including which registers are available. We use this to indicate to the client that registers such as mip, mstatus, and mie exist, and what their offset is.

You may not be able to do "info all" to see the contents of various riscv csrs.

Your gdb is notifying you that the server is reporting it supports target.xml, but your client was built without xml support.
