### ISSUE TITLE
wishbone-tool --server gdb: Reply contains invalid hex digit 116

### ISSUE THREAD

**Issue by mithro** [litex-hub/wishbone-utils#18]
```
(gdb) info all-registers
zero           0x0	0
ra             0x0	0x0 <ptr>
sp             0x3ccc	0x3ccc
gp             0x0	0x0 <ptr>
tp             0x0	0x0 <ptr>
t0             0x0	0
t1             0x0	0
t2             0x0	0
s0             0x0	0x0 <ptr>
s1             0x0	0
a0             0x0	0
a1             0x0	0
a2             0x0	0
a3             0x0	0
a4             0x0	0
a5             0x0	0
a6             0x0	0
a7             0x0	0
s2             0x0	0
s3             0x0	0
s4             0x0	0
s5             0x0	0
s6             0x0	0
s7             0x0	0
s8             0x0	0
s9             0x0	0
s10            0x0	0
s11            0x0	0
t3             0x0	0
t4             0x0	0
t5             0x0	0
t6             0x0	0
pc             0x20028074	0x20028074
Ignoring packet error, continuing...
Reply contains invalid hex digit 116
```

**Comment by xobs** [comment]
My guess is your client is trying to access something like the floating point registers that don't exist.

**Comment by xobs** [comment]
To further elaborate, `pc` is register 32, which is followed by register 33, which is the first floating point register.  Specifically, this is register `ft0`.  For example, the upstream openocd defines this at https://github.com/riscv/riscv-openocd/blob/9886f7737403d2ea378dd3349de4b70b1b62ce54/src/target/riscv/gdb_regs.h#L44

I'm curious to see what requests your gdb is sending to the server.  I'd like to know how we should be properly responding to requests for invalid registers.  Could you try setting `RUST_LOG="debug"` and seeing if there's a command of interest?

**Comment by xobs** [comment]
I modified the gdb server so now it gives a proper error when an invalid register is accessed.  Additionally, an error message is now printed to the console.

**Comment by mithro** [comment]
I wonder if this could be related to #17 issue and the lack of XML support meaning it falls back to a default config which has a FPU?

**Comment by mithro** [comment]
It seems to now give the following;
```
Could not fetch register "ft0"; remote failure reply 'E01'
```

**Comment by mithro** [comment]
And the wishbone-tool outputs;
```
ERROR [wishbone_tool::gdb] Error reading register: invalid register 33
```

So I think this is fixed!
