### ISSUE TITLE
wishbone-tool - Should complained if using gdb and not found in csr.csv file

### ISSUE THREAD

**Issue by mithro** [litex-hub/wishbone-utils#20]
If a `csr.csv` file is provided to `wishbone-tool` and;
 * You asked for `--server gdb` but no vexriscv jtag interfaces is found in the `csr.csv` file it should complain.
 * You asked for `--server terminal` but no uart is found in the `csr.csv` file it should complain.

**Comment by xobs** [comment]
This should now give appropriate errors for the two given conditions:

```
ERROR [wishbone_tool] invalid configuration: GDB specified but no vexriscv address present in csv file
```
