### ISSUE TITLE
Ethernet backend broken in version 0.7.4 and 0.7.5

### ISSUE THREAD

**Issue by cklarhorst** [litex-hub/wishbone-utils#28]
I'm using the `wishbone-tool-v0.7.5-x86_64-unknown-linux-gnu.tar.gz` release file.
For version 0.7.4 and 0.7.5 the command: `wishbone-tool --ethernet-host [ip] --ethernet-tcp 0x0 ` results in 
`Error: "invalid configuration: invalid ethernet address: io error invalid socket address"`
Version 0.7.3 is working fine i.e. yields the expected result:
```
INFO [wishbone_tool::bridge::ethernet] Re-opened ethernet host [ip]:1234
Value at 00000001: 0b00006f
```
Please let me know if I can support you with any more information.

**Comment by xobs** [comment]
Hmm... does it work if you run it like this:

```sh
$ wishbone-tool --ethernet-host ip-address:port --ethernet-tcp 0x0 
```

I.e. add the port onto the command, while still specifying the address-to-read as 0x0? Also, since you're using a tcp connection, this is going to something such as `lxserver`, correct? Or are you connecting to a different host?

**Comment by cklarhorst** [comment]
`wishbone-tool --ethernet-host [ip] --ethernet-port 1234 --ethernet-tcp 0x0` also doesn't work.
And yes I would like to connect to an litex_server. I tried to connect to another host and to an instance on the same machine (using `--ethernet-host 127.0.0.1`) both gave the same error message.

**Comment by xobs** [comment]
Ah, pushing the fix caused it to close the issue.

Version 0.7.6 is building now, which should address the issue. Would you please give it a try when it finishes building (in about 5 minutes) and let me know if it fixes the issue?

**Comment by cklarhorst** [comment]
Thank very much!!

**Comment by xobs** [comment]
I'm going to reopen this issue while I track down build issues. It appears as though something changed recently with cross-compilation.

**Comment by cklarhorst** [comment]
v0.7.7 is working as expected!
